services:
  mongo:
    image: "mongo:latest"
    container_name: "mongo-db-container"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASS}"
      MONGO_INITDB_DATABASE: "${MONGO_DB}"
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"

  backend:
    build:
      context: "./Share&Care"                 # cudzysłowy przez znak &
    container_name: "sharecareapp-backend"
    depends_on:
      - mongo
    environment:
      MongoDb__ConnectionString: "mongodb://${MONGO_APP_USER}:${MONGO_APP_PASS}@mongo:27017/${MONGO_DB}?authSource=${MONGO_AUTH_SOURCE}"
      Auth__Jwt__Key: "${JWT_KEY}"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "7070:8080"
    restart: unless-stopped

volumes:
  mongo_data: